# Generated by Django 4.1.1 on 2022-09-27 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('alter_ego', models.CharField(max_length=30)),
                ('catchphrase', models.CharField(max_length=50)),
                ('super_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype')),
            ],
        ),
         migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
