# Generated by Django 4.1.1 on 2022-09-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='super',
        #     name='power',
        #     field=models.ManyToManyField(to='supers_power'),
        # ),
    ]
