# Generated by Django 4.1.1 on 2022-09-28 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0002_power_remove_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='power',
            field=models.ManyToManyField(to='supers.power'),
        ),
        migrations.AlterField(
            model_name='super',
            name='super_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
            preserve_default=False,
        ),
    ]
